Feature/114 comments
marklogic-community/marklogic-healthcare-starter-kit pull request #5
Opened 2022-01-04 23:20 UTC by damonfeldman

Mostly comments, but also a smaller data set with 100k claim transactions instead of 400k, and gradle tasks to process them.

2022-01-07 20:56 UTC, theflyinggriffin commented
Not sure what this files is, but I don't think it belongs "data/synthea/csv/.DS_Store"

2022-01-07 20:58 UTC, theflyinggriffin requested changes
Remove "data/synthea/csv/.DS_Store"

2022-01-17 16:39 UTC, theflyinggriffin approved these changes

2022-01-18 17:13 UTC, wgehring-ml reviewed
LGTM

2022-01-31 16:49 UTC, merged